name: 'toys_and_models'
version: '1.0.0'
config-version: 2

profile: 'toys_and_models'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  toys_and_models:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table